"""
End-to-end multi-view fit: photos in, object pose + overlay out (bead ...-2ni).

Ties together the pieces that already existed but were never connected to a camera:

    photo → ChArUco detect → board pose (world→camera)   [board_pose]
          → mask board lattice → Canny → edge pixels     [image_edges]
          → fit CAD pose across all views                [multiview]
          → overlay projected CAD edges on the photo     [here]

The **board defines the world frame**, so each photo self-registers: a board-in-shot capture
needs no rig calibration and no simultaneous exposure. The part is static, so "multi-view" only
means several views with known camera poses — one camera moved around the rig satisfies it just
as well as several fixed ones. That is the ground-truth mode of the test cell; production mode
(pre-calibrated fixed extrinsics, board removed) swaps step 2 for stored rig extrinsics.

Lives in ``app/services`` rather than ``tools`` so it is importable by the future capture/fit
endpoint, testable inside the container, and usable from ``tools/fit_multiview.py`` as a thin CLI.
"""
from __future__ import annotations

import json
import os
from typing import Dict, List, Optional, Sequence, Tuple

import numpy as np

try:  # import guard — keep module importable if a wheel is missing
    import cv2

    _CV2_IMPORT_ERROR: Optional[str] = None
except Exception as exc:  # pragma: no cover - import guard
    cv2 = None  # type: ignore
    _CV2_IMPORT_ERROR = str(exc)

from app.services import charuco, image_edges
from app.services.board_pose import charuco_board_pose
from app.services.multiview import fit_object_pose, sample_polylines


class MultiViewFitError(Exception):
    """Raised when a fit cannot be set up (bad profile, no board, resolution mismatch)."""


def _require_cv2() -> None:
    if cv2 is None:  # pragma: no cover
        raise MultiViewFitError(f"OpenCV is not available: {_CV2_IMPORT_ERROR}")


# ── inputs ──────────────────────────────────────────────────────────────────

def load_profile(path: str) -> dict:
    """
    Load a calibration profile written by ``/calibration/compute``.

    Returns ``{name, K, dist, image_size (w,h), board}``. ``image_size`` is stored
    width-first by the calibration router; the resolution gate below depends on that.
    """
    with open(path, "r", encoding="utf-8") as fh:
        p = json.load(fh)
    for key in ("camera_matrix", "dist_coeffs", "image_size"):
        if key not in p:
            raise MultiViewFitError(f"calibration profile '{path}' is missing '{key}'")
    return {
        "name": p.get("name") or os.path.splitext(os.path.basename(path))[0],
        "K": np.asarray(p["camera_matrix"], np.float64).reshape(3, 3),
        "dist": np.asarray(p["dist_coeffs"], np.float64).reshape(-1, 1),
        "image_size": (int(p["image_size"][0]), int(p["image_size"][1])),
        "board": p.get("board") or dict(charuco.DEFAULT_BOARD),
        "rms_reproj_error_px": p.get("rms_reproj_error_px"),
    }


def load_model(path: str) -> dict:
    """Load an AR model export (``outputs/ar_models/*.json``): CAD edges in the OBJECT frame."""
    with open(path, "r", encoding="utf-8") as fh:
        m = json.load(fh)
    if not m.get("edges"):
        raise MultiViewFitError(f"AR model '{path}' has no 'edges'")
    return m


def model_bbox(model: dict) -> Tuple[np.ndarray, np.ndarray]:
    bb = model.get("bbox") or {}
    if "min" in bb and "max" in bb:
        return np.asarray(bb["min"], np.float64), np.asarray(bb["max"], np.float64)
    pts = np.vstack([np.asarray(e, np.float64).reshape(-1, 3) for e in model["edges"]])
    return pts.min(axis=0), pts.max(axis=0)


def board_extent_mm(board) -> Tuple[float, float]:
    """Physical (width, height) of the board in its own frame, from the corner lattice."""
    corners = np.asarray(board.getChessboardCorners(), np.float64).reshape(-1, 3)
    xs, ys = np.unique(np.round(corners[:, 0], 6)), np.unique(np.round(corners[:, 1], 6))
    pitch = float(min(np.min(np.diff(xs)), np.min(np.diff(ys))))
    return float(xs[-1] + pitch), float(ys[-1] + pitch)


def camera_side_of_board(views: Sequence[dict]) -> float:
    """
    Which side of the board plane the cameras are on: ``+1`` or ``-1`` (sign of board Z).

    Not a formality. An OpenCV ChArUco board generated by ``generateImage`` and mapped to
    ``(u, v) -> (X, Y, 0)`` is legible from **negative** board Z — a camera looking at it solves
    to a centre with ``Z < 0``. So "resting on the board" means the object occupies *negative* Z,
    and an init that assumes +Z puts the part through the table where no view can see it.
    Derived from the solved poses rather than hard-coded, so it stays correct if a board, a
    convention or an OpenCV version differs.
    """
    _require_cv2()
    zs = []
    for v in views:
        R, _ = cv2.Rodrigues(np.asarray(v["rvec_cam"], np.float64).reshape(3, 1))
        t = np.asarray(v["tvec_cam"], np.float64).reshape(3, 1)
        zs.append(float((-R.T @ t).ravel()[2]))
    if not zs:
        return -1.0
    return 1.0 if float(np.mean(zs)) > 0 else -1.0


def default_init_pose(
    model: dict,
    board,
    views: Optional[Sequence[dict]] = None,
) -> Tuple[np.ndarray, np.ndarray]:
    """
    A nominal starting pose: object resting on the board, centred on it in X/Y, unrotated.

    Pass *views* so the object is placed on the side of the board the cameras are actually on
    (see :func:`camera_side_of_board`); without them the OpenCV convention (-Z) is assumed.

    This is only a *starting guess*, and translation-only — it does not know which way up the
    model is. The edge cost has a narrow basin, so always eyeball the init overlay before
    trusting a fit, and pass an explicit init when the part is placed differently. Locating
    stops on the rig are what make a default like this reliable run-to-run.
    """
    lo, hi = model_bbox(model)
    bw, bh = board_extent_mm(board)
    centre = (lo + hi) / 2.0
    z_sign = camera_side_of_board(views) if views else -1.0
    # Seat the bbox face nearest the board plane onto Z=0, body extending toward the cameras.
    tz = -lo[2] if z_sign > 0 else -hi[2]
    tvec = np.array([bw / 2.0 - centre[0], bh / 2.0 - centre[1], tz], np.float64).reshape(3, 1)
    return np.zeros((3, 1), np.float64), tvec


# ── per-photo view construction ─────────────────────────────────────────────

def keep_to_exclude(keep: np.ndarray, exclude: Optional[np.ndarray]) -> np.ndarray:
    """Combine a KEEP mask with an existing EXCLUDE mask into a single exclude mask."""
    inverted = np.where(keep > 0, 0, 255).astype(np.uint8)
    return inverted if exclude is None else np.maximum(inverted, exclude)


def build_view(
    image: np.ndarray,
    profile: dict,
    board,
    detector,
    *,
    label: str = "",
    mask_mode: str = "grid",
    band_px: int = 7,
    blur_ksize: int = 5,
    canny_low: Optional[int] = None,
    canny_high: Optional[int] = None,
    max_points: Optional[int] = None,
    min_corners: int = 6,
    enforce_resolution: bool = True,
    working_margin_mm: Optional[float] = 150.0,
) -> dict:
    """
    Turn one photo into a view dict for ``fit_object_pose``, plus diagnostics.

    Returns ``{K, dist, rvec_cam, tvec_cam, edge_pixels, _diag}``. The camera pose is the
    **board→camera** pose, which is world→camera with the board as the world frame.
    """
    _require_cv2()
    h, w = image.shape[:2]
    pw, ph = profile["image_size"]
    if enforce_resolution and (w, h) != (pw, ph):
        raise MultiViewFitError(
            f"{label or 'photo'} is {w}x{h} but calibration profile '{profile['name']}' was "
            f"computed at {pw}x{ph}. Intrinsics do not transfer across resolutions — reshoot at "
            f"the calibrated size or recalibrate."
        )

    gray = image_edges.to_gray(image)
    corners, ids, marker_corners, _marker_ids = charuco.detect_board_detailed(detector, gray)
    if ids is None or len(ids) < min_corners:
        n = 0 if ids is None else int(len(ids))
        raise MultiViewFitError(
            f"{label or 'photo'}: only {n} ChArUco corners detected (need >={min_corners}). "
            f"Check the board dictionary matches the printed board ({profile['board'].get('dictionary')}) "
            f"and that the board fills enough of the frame."
        )

    rvec_cam, tvec_cam, n_corners = charuco_board_pose(
        corners, ids, board, profile["K"], profile["dist"], min_corners=min_corners
    )

    exclude = None
    if mask_mode == "grid":
        exclude = image_edges.board_grid_mask(
            board, rvec_cam, tvec_cam, profile["K"], profile["dist"], (h, w), band_px=band_px
        )
    elif mask_mode == "hull":
        exclude = image_edges.marker_hull_mask(marker_corners, (h, w))
    elif mask_mode != "none":
        raise MultiViewFitError(f"unknown mask_mode '{mask_mode}' (expected grid|hull|none)")

    # Confine the search to the volume the part can occupy. Without this the rig's own rails
    # out-compete the part: they are longer, straighter and brighter than anything on it.
    keep = None
    if working_margin_mm is not None:
        keep = image_edges.working_area_mask(
            board, rvec_cam, tvec_cam, profile["K"], profile["dist"], (h, w),
            margin_mm=working_margin_mm,
        )
        exclude = keep_to_exclude(keep, exclude)

    pix = image_edges.detect_edge_pixels(
        image,
        blur_ksize=blur_ksize,
        low=canny_low,
        high=canny_high,
        exclude_mask=exclude,
        max_points=max_points,
    )

    masked_frac = float(np.count_nonzero(exclude) / (h * w)) if exclude is not None else 0.0
    kept_frac = float(np.count_nonzero(keep) / (h * w)) if keep is not None else 1.0
    return {
        "K": profile["K"],
        "dist": profile["dist"],
        "rvec_cam": rvec_cam,
        "tvec_cam": tvec_cam,
        "edge_pixels": pix,
        "width": w,
        "height": h,
        "_diag": {
            "label": label,
            "profile": profile["name"],
            "resolution": [int(w), int(h)],
            "board_corners": int(n_corners),
            "edge_pixels": int(len(pix)),
            "mask_mode": mask_mode,
            "masked_fraction": round(masked_frac, 4),
            "working_area_fraction": round(kept_frac, 4),
            "camera_distance_mm": round(float(np.linalg.norm(tvec_cam)), 1),
        },
    }


# ── drawing ─────────────────────────────────────────────────────────────────

def _densify(polyline: np.ndarray, max_step: float) -> np.ndarray:
    """Insert points so no 3D gap exceeds *max_step* — keeps projected lines curved correctly."""
    pts = np.asarray(polyline, np.float64).reshape(-1, 3)
    if len(pts) < 2:
        return pts
    out = []
    for a, b in zip(pts[:-1], pts[1:]):
        seg = b - a
        n = max(1, int(np.ceil(np.linalg.norm(seg) / max_step)))
        out.extend(a + seg * (k / n) for k in range(n))
    out.append(pts[-1])
    return np.asarray(out, np.float64)


def project_model_edges(
    model: dict,
    rvec_obj,
    tvec_obj,
    view: dict,
    *,
    max_step: float = 5.0,
) -> List[np.ndarray]:
    """Project the model's edge polylines into a view at a given object pose → list of Nx2."""
    _require_cv2()
    R_cam, _ = cv2.Rodrigues(np.asarray(view["rvec_cam"], np.float64).reshape(3, 1))
    t_cam = np.asarray(view["tvec_cam"], np.float64).reshape(3, 1)
    R_obj, _ = cv2.Rodrigues(np.asarray(rvec_obj, np.float64).reshape(3, 1))
    t_obj = np.asarray(tvec_obj, np.float64).reshape(3, 1)
    R_oc = R_cam @ R_obj
    t_oc = R_cam @ t_obj + t_cam
    rvec_oc, _ = cv2.Rodrigues(R_oc)

    out = []
    for pl in model["edges"]:
        pts = _densify(pl, max_step)
        if len(pts) < 2:
            continue
        proj, _ = cv2.projectPoints(pts.reshape(-1, 1, 3), rvec_oc, t_oc, view["K"], view["dist"])
        out.append(proj.reshape(-1, 2))
    return out


def render_overlay(
    image: np.ndarray,
    model: dict,
    view: dict,
    poses: Sequence[Tuple[str, object, object, Tuple[int, int, int]]],
    *,
    thickness: int = 2,
    show_edge_pixels: bool = True,
    edge_pixel_colour: Tuple[int, int, int] = (170, 60, 170),
) -> np.ndarray:
    """
    Draw one or more posed wireframes over a photo.

    *poses*: ``(label, rvec, tvec, bgr_colour)`` — e.g. the init in amber and the fit in cyan.
    Coincident overlays need distinct colours (a lesson from the marker auto-registration work),
    so pass visibly different ones and they are listed in a legend.

    The detected edge pixels are painted magenta underneath, which is the diagnostic that matters
    most when a fit goes wrong: it shows what the solver was actually matching against, so a fit
    that latched onto the board, a shadow or a table edge is obvious at a glance.
    """
    _require_cv2()
    canvas = image.copy() if image.ndim == 3 else cv2.cvtColor(image, cv2.COLOR_GRAY2BGR)

    if show_edge_pixels and len(view.get("edge_pixels", [])):
        pix = np.round(np.asarray(view["edge_pixels"])).astype(int)
        h, w = canvas.shape[:2]
        ok = (pix[:, 0] >= 0) & (pix[:, 0] < w) & (pix[:, 1] >= 0) & (pix[:, 1] < h)
        canvas[pix[ok, 1], pix[ok, 0]] = edge_pixel_colour

    for i, (label, rvec, tvec, colour) in enumerate(poses):
        for poly in project_model_edges(model, rvec, tvec, view):
            pts = np.round(poly).astype(np.int32)
            cv2.polylines(canvas, [pts], isClosed=False, color=colour, thickness=thickness,
                          lineType=cv2.LINE_AA)
        y = 40 + i * 38
        cv2.putText(canvas, label, (20, y), cv2.FONT_HERSHEY_SIMPLEX, 1.1, (0, 0, 0), 5, cv2.LINE_AA)
        cv2.putText(canvas, label, (20, y), cv2.FONT_HERSHEY_SIMPLEX, 1.1, colour, 2, cv2.LINE_AA)
    return canvas


# ── the whole job ───────────────────────────────────────────────────────────

CAP_PX = 60.0        # coarse-search distance cap: beyond this, a point is simply 'wrong'
INIT_COLOUR = (0, 165, 255)      # amber (BGR)
FIT_COLOUR = (255, 255, 0)       # cyan  (BGR)


def working_volume_bounds(model: dict, board, views: Optional[Sequence[dict]] = None):
    """
    Bounds on the object translation: the physical volume the part can plausibly occupy.

    Without these the edge cost has a degenerate global minimum — push the object far enough
    away and it projects into a handful of pixels, each landing near SOME detected edge, so the
    residual collapses. On the first real capture the solver "improved" 318 -> 5.2 px by moving
    a 433 mm part to 4.4 metres and shrinking it to a dot.

    The box spans the board plus one model-length of slack in each direction (the part may sit
    beside the board, not on it), and one model-height either side of the board plane, on the
    camera side.
    """
    lo, hi = model_bbox(model)
    bw, bh = board_extent_mm(board)
    slack = float(np.max(hi - lo))
    z_sign = camera_side_of_board(views) if views else -1.0
    depth = slack
    if z_sign > 0:
        z_lo, z_hi = -depth * 0.25, depth
    else:
        z_lo, z_hi = -depth, depth * 0.25
    return (
        np.array([-slack, -slack, z_lo], np.float64),
        np.array([bw + slack, bh + slack, z_hi], np.float64),
    )


def coarse_search(
    views: List[dict],
    model: dict,
    board,
    *,
    step_mm: float = 100.0,
    yaw_step_deg: float = 20.0,
    sample_mm: float = 40.0,
    base_rvec=None,
):
    """
    Grid-search the object's (x, y, yaw) for a starting pose, and return the best.

    The edge cost is a *local* optimiser with a narrow basin, so the init decides everything —
    on the first real capture a default init 300 mm from the truth converged to nonsense. But
    the part lies flat on a plane, so the genuinely unknown parameters are only its position in
    that plane and its rotation about the plane normal. Three dimensions is small enough to
    simply scan.

    This *evaluates* the cost on the grid rather than optimising at each node — one residual
    evaluation per candidate instead of a few hundred — using a coarsely sampled model. That
    makes a few thousand candidates affordable, and the winner is then refined properly.
    """
    _require_cv2()

    obj_pts = sample_polylines(model["edges"], max_step=sample_mm)
    lo, hi = model_bbox(model)
    centre = (lo + hi) / 2.0
    bw, bh = board_extent_mm(board)
    slack = float(np.max(hi - lo))
    z_sign = camera_side_of_board(views)
    tz = -lo[2] if z_sign > 0 else -hi[2]

    # Score against a distance transform rather than a KD-tree. Each candidate then costs one
    # array lookup per sample point instead of a nearest-neighbour query, which is what makes
    # scanning a few thousand candidates practical at all — a KD-tree version of this same grid
    # was still running after three minutes.
    prepared = []
    for v in views:
        w, h = int(v["width"]), int(v["height"])
        edge_img = np.zeros((h, w), np.uint8)
        p = np.round(np.asarray(v["edge_pixels"], np.float64)).astype(int)
        ok = (p[:, 0] >= 0) & (p[:, 0] < w) & (p[:, 1] >= 0) & (p[:, 1] < h)
        edge_img[p[ok, 1], p[ok, 0]] = 255
        dt = cv2.distanceTransform(255 - edge_img, cv2.DIST_L2, 3)
        R_cam, _ = cv2.Rodrigues(np.asarray(v["rvec_cam"], np.float64).reshape(3, 1))
        prepared.append((R_cam, np.asarray(v["tvec_cam"], np.float64).reshape(3, 1),
                         v["K"], v["dist"], dt, w, h))

    base = np.zeros(3) if base_rvec is None else np.asarray(base_rvec, np.float64).reshape(3)
    R_base, _ = cv2.Rodrigues(base.reshape(3, 1))

    xs = np.arange(-slack * 0.5, bw + slack * 0.5 + step_mm, step_mm)
    ys = np.arange(-slack * 0.5, bh + slack * 0.5 + step_mm, step_mm)
    yaws = np.radians(np.arange(0.0, 360.0, yaw_step_deg))

    best = (np.inf, base, np.array([0.0, 0.0, tz]))
    for yaw in yaws:
        Rz, _ = cv2.Rodrigues(np.array([[0.0], [0.0], [yaw]]))
        R_obj = Rz @ R_base
        rvec_obj, _ = cv2.Rodrigues(R_obj)
        rotated_centre = R_obj @ centre.reshape(3, 1)
        for x in xs:
            for y in ys:
                # Place the object's centroid at (x, y) so the grid means the same thing at
                # every yaw, rather than sweeping the model's arbitrary origin around.
                t = np.array([[x], [y], [tz]]) - rotated_centre
                t[2] = tz
                total, n = 0.0, 0
                for R_cam, t_cam, K, dist, dt, w, h in prepared:
                    R_oc = R_cam @ R_obj
                    t_oc = R_cam @ t + t_cam
                    if t_oc[2, 0] <= 1.0:              # behind the camera
                        total, n = np.inf, 1
                        break
                    rvec_oc, _ = cv2.Rodrigues(R_oc)
                    proj, _ = cv2.projectPoints(obj_pts.reshape(-1, 1, 3), rvec_oc, t_oc, K, dist)
                    q = proj.reshape(-1, 2)
                    xi = np.clip(np.round(q[:, 0]).astype(np.int32), 0, w - 1)
                    yi = np.clip(np.round(q[:, 1]).astype(np.int32), 0, h - 1)
                    d = dt[yi, xi]
                    # Points projecting outside the frame get the cap, so a candidate cannot
                    # win by hiding most of the model off-image.
                    off = (q[:, 0] < 0) | (q[:, 0] >= w) | (q[:, 1] < 0) | (q[:, 1] >= h)
                    d = np.where(off, CAP_PX, np.minimum(d, CAP_PX))
                    total += float(np.sum(d ** 2))
                    n += len(d)
                score = total / max(n, 1)
                if score < best[0]:
                    best = (score, rvec_obj.reshape(3), t.reshape(3))
    return best[1].reshape(3, 1), best[2].reshape(3, 1), float(np.sqrt(best[0]))


def fit_from_views(
    views: List[dict],
    model: dict,
    init_rvec,
    init_tvec,
    *,
    max_step: float = 2.0,
    huber_delta: float = 10.0,
    max_nfev: int = 400,
    tvec_bounds=None,
) -> dict:
    """Run the solver over prepared views and return pose + diagnostics."""
    rvec, tvec, info = fit_object_pose(
        views, model["edges"], init_rvec, init_tvec,
        max_step=max_step, huber_delta=huber_delta, max_nfev=max_nfev,
        tvec_bounds=tvec_bounds,
    )
    return {
        "rvec": np.asarray(rvec).reshape(3).tolist(),
        "tvec": np.asarray(tvec).reshape(3).tolist(),
        "info": info,
        "views": [v["_diag"] for v in views],
        "model": {
            "name": model.get("name"),
            "scale": model.get("scale"),
            "edges": len(model["edges"]),
        },
    }
