version: "3.8"

services:
  api:
    build: .
    container_name: cad_api
    volumes:
      - ./app:/app/app
      - ./uploads:/app/uploads
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
